In [48]:
import os
import pandas as pd
file1="/allen/aics/microscopy/PRODUCTION/PipelineMetaData/PlateLayout.csv"
df_plate_layout = pd.read_csv(file1, sep=',', header=0, names=['PlateLayoutID','column_id','row_id','well_id','contents','concentration','CellLine','clone_id','well_type','dyes_applied'])
df_plate_layout

,PlateLayoutID,column_id,row_id,well_id,contents,concentration,CellLine,clone_id,well_type,dyes_applied
0,L3500000392,1,A,A1,empty,NaN,NaN,NaN,empty,none
1,L3500000392,2,A,A2,empty,NaN,NaN,NaN,empty,none
2,L3500000392,3,A,A3,empty,NaN,NaN,NaN,empty,none
3,L3500000392,4,A,A4,empty,NaN,NaN,NaN,empty,none
4,L3500000392,5,A,A5,empty,NaN,NaN,NaN,empty,none
5,L3500000392,6,A,A6,empty,NaN,NaN,NaN,empty,none
6,L3500000392,7,A,A7,empty,NaN,NaN,NaN,empty,none
7,L3500000392,8,A,A8,empty,NaN,NaN,NaN,empty,none
8,L3500000392,9,A,A9,empty,NaN,NaN,NaN,empty,none
9,L3500000392,10,A,A10,empty,NaN,NaN,NaN,empty,none
10,L3500000392,11,A,A11,empty,NaN,NaN,NaN,empty,none
11,L3500000392,12,A,A12,empty,NaN,NaN,NaN,empty,none
12,L3500000392,1,B,B1,empty,NaN,NaN,NaN,empty,none
13,L3500000392,2,B,B2,empty,NaN,NaN,NaN,empty,none
14,L3500000392,3,B,B3,empty,NaN,NaN,NaN,empty,none
15,L3500000392,4,B,B4,empty,NaN,NaN,NaN,empty,none
16,L3500000392,5,B,B5,empty,NaN,NaN,NaN,empty,none
17,L3500000392,6,B,B6,empty,NaN,NaN,NaN,empty,none
18,L3500000392,7,B,B7,empty,NaN,NaN,NaN,empty,none
19,L3500000392,8,B,B8,empty,NaN,NaN,NaN,empty,none
20,L3500000392,9,B,B9,empty,NaN,NaN,NaN,empty,none
21,L3500000392,10,B,B10,empty,NaN,NaN,NaN,empty,none
22,L3500000392,11,B,B11,empty,NaN,NaN,NaN,empty,none
23,L3500000392,12,B,B12,empty,NaN,NaN,NaN,empty,none
24,L3500000392,1,C,C1,empty,NaN,NaN,NaN,empty,none
25,L3500000392,2,C,C2,empty,NaN,NaN,NaN,empty,none
26,L3500000392,3,C,C3,empty,NaN,NaN,NaN,empty,none
27,L3500000392,4,C,C4,empty,NaN,NaN,NaN,empty,none
28,L3500000392,5,C,C5,AICS-12,2000.0,12.0,101,pos_control,NaN
29,L3500000392,6,C,C6,AICS-12,2000.0,12.0,101,pos_control,NaN
...,...,...,...,...,...,...,...,...,...,...
5826,L3500000970,7,F,F7,AICS-13,2500.0,11.0,27,exp,NaN
5827,L3500000970,8,F,F8,AICS-13,2500.0,11.0,27,exp,NaN
5828,L3500000970,9,F,F9,Fluorescein,100.0,NaN,none,488nm_ff,NaN
5829,L3500000970,10,F,F10,empty,NaN,NaN,NaN,empty,NaN
5830,L3500000970,11,F,F11,empty,NaN,NaN,NaN,empty,NaN
5831,L3500000970,12,F,F12,empty,NaN,NaN,NaN,empty,NaN
5832,L3500000970,1,G,G1,empty,NaN,NaN,NaN,empty,NaN
5833,L3500000970,2,G,G2,empty,NaN,NaN,NaN,empty,NaN
5834,L3500000970,3,G,G3,empty,NaN,NaN,NaN,empty,NaN
5835,L3500000970,4,G,G4,empty,NaN,NaN,NaN,empty,NaN
5836,L3500000970,5,G,G5,empty,NaN,NaN,NaN,empty,NaN
5837,L3500000970,6,G,G6,empty,NaN,NaN,NaN,empty,NaN
5838,L3500000970,7,G,G7,empty,NaN,NaN,NaN,empty,NaN
5839,L3500000970,8,G,G8,empty,NaN,NaN,NaN,empty,NaN
5840,L3500000970,9,G,G9,beads,NaN,NaN,none,psf,NaN
5841,L3500000970,10,G,G10,empty,NaN,NaN,NaN,empty,NaN
5842,L3500000970,11,G,G11,empty,NaN,NaN,NaN,empty,NaN
5843,L3500000970,12,G,G12,empty,NaN,NaN,NaN,empty,NaN
5844,L3500000970,1,H,H1,empty,NaN,NaN,NaN,empty,NaN
5845,L3500000970,2,H,H2,empty,NaN,NaN,NaN,empty,NaN
5846,L3500000970,3,H,H3,empty,NaN,NaN,NaN,empty,NaN
5847,L3500000970,4,H,H4,empty,NaN,NaN,NaN,empty,NaN
5848,L3500000970,5,H,H5,empty,NaN,NaN,NaN,empty,NaN
5849,L3500000970,6,H,H6,empty,NaN,NaN,NaN,empty,NaN
5850,L3500000970,7,H,H7,empty,NaN,NaN,NaN,empty,NaN
5851,L3500000970,8,H,H8,empty,NaN,NaN,NaN,empty,NaN
5852,L3500000970,9,H,H9,empty,NaN,NaN,NaN,empty,NaN
5853,L3500000970,10,H,H10,empty,NaN,NaN,NaN,empty,NaN
5854,L3500000970,11,H,H11,empty,NaN,NaN,NaN,empty,NaN
5855,L3500000970,12,H,H12,empty,NaN,NaN,NaN,empty,NaN

In [47]:
file2="/allen/aics/microscopy/PRODUCTION/PipelineMetaData/Pipelines.csv"
df_pipeline = pd.read_csv(file2, sep=',', header=0, names=['PipelineID','ExperimentID','PlateID','PlateLayoutID','SplitDate(Pipeline Exp label)','DescriptionPipeline','DescriptionExperiment','WebLink','ChosenForPlating'])
df_pipeline

,PipelineID,ExperimentID,PlateID,PlateLayoutID,SplitDate(Pipeline Exp label),DescriptionPipeline,DescriptionExperiment,WebLink,ChosenForPlating
0,1,Exp1_20161021_Seed,3500000210,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
1,1,Exp1_20161021_Seed,3500000211,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
2,1,Exp1_20161021_Seed,3500000212,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
3,1,Exp1_20161021_Seed,3500000213,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
4,1,Exp1_20161021_Seed,3500000214,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
5,1,Exp1_20161021_Seed,3500000215,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
6,1,Exp1_20161021_Seed,3500000216,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
7,1,Exp1_20161021_Seed,3500000217,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
8,1,Exp1_20161021_Seed,3500000218,90916,10/21/2016,Scale up 96 well plate cell seeding.,Compare manual and robot seeding. All Matrigel...,http://aicstest.atlassian.net/wiki/display/MIC...,1
9,1,Exp2_20161025_Seed,3500000219,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
10,1,Exp2_20161025_Seed,3500000221,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
11,1,Exp2_20161025_Seed,3500000222,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
12,1,Exp2_20161025_Seed,3500000223,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
13,1,Exp2_20161025_Seed,3500000224,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
14,1,Exp2_20161025_Seed,3500000225,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
15,1,Exp3_20161028_Seed,3500000227,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
16,1,Exp3_20161028_Seed,3500000228,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
17,1,Exp3_20161028_Seed,3500000231,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
18,1,Exp2_20161025_Seed,3500000232,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
19,1,Exp2_20161025_Seed,3500000233,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
20,1,Exp2_20161025_Seed,3500000234,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
21,1,Exp3_20161028_Seed,3500000235,90916,10/28/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
22,1,Exp3_20161028_Seed,3500000236,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
23,1,Exp3_20161028_Seed,3500000237,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
24,1,Exp3_20161028_Seed,3500000238,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
25,1,Exp3_20161028_Seed,3500000239,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
26,1,Exp3_20161028_Seed,3500000240,L3500000222,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
27,1,Exp3_20161028_Seed,3500000241,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
28,1,Exp3_20161028_Seed,3500000242,90916,10/25/2016,Scale up 96 well plate cell seeding.,Establish baseline cell quality by hand and fr...,http://aicstest.atlassian.net/wiki/display/MIC...,1
29,1,Exp4_20161031_Seed,3500000243,90916,10/31/2016,Scale up 96 well plate cell seeding.,Second plating with increased mixing/non-EVA b...,http://aicstest.atlassian.net/wiki/display/MIC...,1
...,...,...,...,...,...,...,...,...,...
679,4,4_20170612_Seed,3500000996,L3500000959,6/16/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
680,4,4_20170612_Seed,3500000997,L3500000959,6/16/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
681,4,4_20170619_Seed,3500001002,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
682,4,4_20170619_Seed,3500001001,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
683,4,4_20170619_Seed,3500001000,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
684,4,4_20170619_Seed,3500000999,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
685,4,4_20170619_Seed,3500000998,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
686,4,4_20170619_Seed,3500001005,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
687,4,4_20170619_Seed,3500001004,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
688,4,4_20170619_Seed,3500001003,L3500000959,6/19/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
689,4,4_20170619_seed,3500001007,L3500000970,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
690,4,4_20170619_seed,3500001008,L3500000970,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
691,4,4_20170619_seed,3500001009,L3500000970,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
692,4,4_20170619_seed,3500001010,L3500000970,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
693,4,4_20170619_seed,3500001006,L3500000959,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
694,4,4_20170619_seed,3500001011,L3500000959,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
695,4,4_20170619_seed,3500001012,L3500000959,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
696,4,4_20170619_seed,3500001013,L3500000959,6/22/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
697,4,4_20170619_seed,3500001015,L3500000970,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
698,4,4_20170619_seed,3500001016,L3500000970,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
699,4,4_20170619_seed,3500001017,L3500000970,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
700,4,4_20170619_seed,3500001018,L3500000970,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
701,4,4_20170619_seed,3500001014,L3500000959,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
702,4,4_20170619_seed,3500001019,L3500000959,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
703,4,4_20170619_seed,3500001020,L3500000959,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
704,4,4_20170619_seed,3500001021,L3500000959,6/23/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
705,4,4_20170622_seed,3500001022,L3500000959,6/26/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
706,4,4_20170622_seed,3500001023,L3500000959,6/26/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
707,4,4_20170622_seed,3500001024,L3500000959,6/26/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1
708,4,4_20170622_seed,3500001025,L3500000959,6/26/2017,Implement pipeline automation.,Imaging of edited Tom-20 line.,robot,1

In [39]:
df_pipeline_plate_layout = pd.merge(df_plate_layout, df_pipeline, on='PlateLayoutID')

In [40]:
image_dir = "/allen/aics/microscopy/PRODUCTION/PIPELINE_Pilot_09292016/3500000971/3500000971_Scan 6-13-2017 6-17-12 AM_Export 6-13-2017 7-22-28 AM/"
import glob
[os.path.basename(p) for p in glob.glob("%s*.tiff" % image_dir) ]

['3500000971_SA_F_8_Ch1.tiff',
 '3500000971_SA_C_6_Ch1.tiff',
 '3500000971_SA_D_5_Ch1.tiff',
 '3500000971_SA_E_4_Ch1.tiff',
 '3500000971_SA_C_4_Ch1.tiff',
 '3500000971_SA_F_7_Ch1.tiff',
 '3500000971_SA_C_7_Ch1.tiff',
 '3500000971_SA_F_5_Ch1.tiff',
 '3500000971_SA_D_7_Ch1.tiff',
 '3500000971_SA_F_4_Ch1.tiff',
 '3500000971_SA_E_6_Ch1.tiff',
 '3500000971_SA_D_4_Ch1.tiff',
 '3500000971_SA_E_5_Ch1.tiff',
 '3500000971_SA_D_8_Ch1.tiff',
 '3500000971_SA_E_7_Ch1.tiff',
 '3500000971_SA_E_8_Ch1.tiff',
 '3500000971_SA_F_6_Ch1.tiff',
 '3500000971_SA_C_5_Ch1.tiff',
 '3500000971_SA_C_8_Ch1.tiff',
 '3500000971_SA_D_6_Ch1.tiff']

In [41]:
import re
prog = re.compile('(\d+)_SA_([A-Z])_(\d)_Ch1\.tiff')
def plate_well(fname):
    sr = prog.match(fname)
    return (sr.group(1), sr.group(2)+sr.group(3))
plate_well('3500000971_SA_F_8_Ch1.tiff')

('3500000971', 'F8')

In [42]:
def three_tuple(fname, plate_well_pair):
    return (fname, plate_well_pair[0], plate_well_pair[1])

file_plate_well_list = [three_tuple(os.path.basename(p), plate_well(os.path.basename(p))) for p in glob.glob("%s*.tiff" % image_dir) ]

In [43]:
import numpy as np
file_names = [f for f,p,w in file_plate_well_list]
plate_ids = [np.int64(p) for f,p,w in file_plate_well_list]
well_ids = [w for f,p,w in file_plate_well_list]
df_images = pd.DataFrame({'FileName': file_names, 'PlateID': plate_ids, 'WellID': well_ids})

In [44]:
df_image_pipeline_plate_layout = pd.merge(df_images, df_pipeline_plate_layout, how='left', left_on = ['PlateID','WellID'], right_on=['PlateID','well_id'])

In [45]:
file3="/allen/aics/microscopy/PRODUCTION/PipelineMetaData/SourcePlates.csv"
df_source_plates = pd.read_csv(file3, sep=',', header=0, names=['ExperimentID','SourcePlateID','Description','CellLine','clone_id','PassageNumber','DonorPassageNumber','PlateType','Maintainer','CoatingType','CoatingLot','CoatingDate','CoatingMethod','CellBatch','SourceVial','SourcePlate','CellCount (Vicell)','SeedingDensity','CellViability','SeedDate','FeedDate','SplitDate(Pipeline Exp label)','GE Score','GE_Initial','M_Score','M_Initial','Notes','ChosenForPlating','ImageLink','y','z'])
df_source_plates['ExperimentID'] = df_source_plates['ExperimentID'].map(lambda x: x.lower())
df_source_plates
df7 = pd.merge(df_image_pipeline_plate_layout, df_source_plates, how='left', left_on = ['ExperimentID'], right_on=['ExperimentID'])
df7 = df7[(df7['GE Score'] == "Pass")]
result = df7[['FileName','PlateID', 'PassageNumber', 'WellID','contents','PlateType','concentration', 
     'CellLine_x', 'CellLine_y', 'Maintainer', 'GE_Initial','CellCount (Vicell)',
     'SeedDate', 'well_type']]
print (result)
#df7
result.to_csv('/home/thusharaw/imagemetadata.csv')

                       FileName     PlateID  PassageNumber WellID contents  \
0    3500000971_SA_F_8_Ch1.tiff  3500000971             27     F8  AICS-13
2    3500000971_SA_F_8_Ch1.tiff  3500000971             27     F8  AICS-13
4    3500000971_SA_F_8_Ch1.tiff  3500000971             33     F8  AICS-13
6    3500000971_SA_F_8_Ch1.tiff  3500000971             33     F8  AICS-13
9    3500000971_SA_F_8_Ch1.tiff  3500000971             37     F8  AICS-13
11   3500000971_SA_F_8_Ch1.tiff  3500000971             37     F8  AICS-13
12   3500000971_SA_C_6_Ch1.tiff  3500000971             27     C6   AICS-0
14   3500000971_SA_C_6_Ch1.tiff  3500000971             27     C6   AICS-0
16   3500000971_SA_C_6_Ch1.tiff  3500000971             33     C6   AICS-0
18   3500000971_SA_C_6_Ch1.tiff  3500000971             33     C6   AICS-0
21   3500000971_SA_C_6_Ch1.tiff  3500000971             37     C6   AICS-0
23   3500000971_SA_C_6_Ch1.tiff  3500000971             37     C6   AICS-0
24   3500000971_SA_D_5_Ch1.tiff  3500000971             27     D5  AICS-12
26   3500000971_SA_D_5_Ch1.tiff  3500000971             27     D5  AICS-12
28   3500000971_SA_D_5_Ch1.tiff  3500000971             33     D5  AICS-12
30   3500000971_SA_D_5_Ch1.tiff  3500000971             33     D5  AICS-12
33   3500000971_SA_D_5_Ch1.tiff  3500000971             37     D5  AICS-12
35   3500000971_SA_D_5_Ch1.tiff  3500000971             37     D5  AICS-12
36   3500000971_SA_E_4_Ch1.tiff  3500000971             27     E4  AICS-13
38   3500000971_SA_E_4_Ch1.tiff  3500000971             27     E4  AICS-13
40   3500000971_SA_E_4_Ch1.tiff  3500000971             33     E4  AICS-13
42   3500000971_SA_E_4_Ch1.tiff  3500000971             33     E4  AICS-13
45   3500000971_SA_E_4_Ch1.tiff  3500000971             37     E4  AICS-13
47   3500000971_SA_E_4_Ch1.tiff  3500000971             37     E4  AICS-13
48   3500000971_SA_C_4_Ch1.tiff  3500000971             27     C4   AICS-0
50   3500000971_SA_C_4_Ch1.tiff  3500000971             27     C4   AICS-0
52   3500000971_SA_C_4_Ch1.tiff  3500000971             33     C4   AICS-0
54   3500000971_SA_C_4_Ch1.tiff  3500000971             33     C4   AICS-0
57   3500000971_SA_C_4_Ch1.tiff  3500000971             37     C4   AICS-0
59   3500000971_SA_C_4_Ch1.tiff  3500000971             37     C4   AICS-0
..                          ...         ...            ...    ...      ...
180  3500000971_SA_E_8_Ch1.tiff  3500000971             27     E8  AICS-13
182  3500000971_SA_E_8_Ch1.tiff  3500000971             27     E8  AICS-13
184  3500000971_SA_E_8_Ch1.tiff  3500000971             33     E8  AICS-13
186  3500000971_SA_E_8_Ch1.tiff  3500000971             33     E8  AICS-13
189  3500000971_SA_E_8_Ch1.tiff  3500000971             37     E8  AICS-13
191  3500000971_SA_E_8_Ch1.tiff  3500000971             37     E8  AICS-13
192  3500000971_SA_F_6_Ch1.tiff  3500000971             27     F6  AICS-13
194  3500000971_SA_F_6_Ch1.tiff  3500000971             27     F6  AICS-13
196  3500000971_SA_F_6_Ch1.tiff  3500000971             33     F6  AICS-13
198  3500000971_SA_F_6_Ch1.tiff  3500000971             33     F6  AICS-13
201  3500000971_SA_F_6_Ch1.tiff  3500000971             37     F6  AICS-13
203  3500000971_SA_F_6_Ch1.tiff  3500000971             37     F6  AICS-13
204  3500000971_SA_C_5_Ch1.tiff  3500000971             27     C5   AICS-0
206  3500000971_SA_C_5_Ch1.tiff  3500000971             27     C5   AICS-0
208  3500000971_SA_C_5_Ch1.tiff  3500000971             33     C5   AICS-0
210  3500000971_SA_C_5_Ch1.tiff  3500000971             33     C5   AICS-0
213  3500000971_SA_C_5_Ch1.tiff  3500000971             37     C5   AICS-0
215  3500000971_SA_C_5_Ch1.tiff  3500000971             37     C5   AICS-0
216  3500000971_SA_C_8_Ch1.tiff  3500000971             27     C8   AICS-0
218  3500000971_SA_C_8_Ch1.tiff  3500000971             27     C8   AICS-0
220  3500000971_SA_C_8_Ch1.tiff  3500000971             33     C8   AICS-0
222  3500000971_SA_C_8_Ch1.tiff  3500000971             33     C8   AICS-0
225  3500000971_SA_C_8_Ch1.tiff  3500000971             37     C8   AICS-0
227  3500000971_SA_C_8_Ch1.tiff  3500000971             37     C8   AICS-0
228  3500000971_SA_D_6_Ch1.tiff  3500000971             27     D6  AICS-12
230  3500000971_SA_D_6_Ch1.tiff  3500000971             27     D6  AICS-12
232  3500000971_SA_D_6_Ch1.tiff  3500000971             33     D6  AICS-12
234  3500000971_SA_D_6_Ch1.tiff  3500000971             33     D6  AICS-12
237  3500000971_SA_D_6_Ch1.tiff  3500000971             37     D6  AICS-12
239  3500000971_SA_D_6_Ch1.tiff  3500000971             37     D6  AICS-12

    PlateType  concentration  CellLine_x  CellLine_y Maintainer    GE_Initial  \
0        10cm         2500.0        11.0           0         JT        Maggie
2        10cm         2500.0        11.0           0         JT  Maggie/Angel
4        10cm         2500.0        11.0          12         JT        Maggie
6        10cm         2500.0        11.0          12         JT        Maggie
9        10cm         2500.0        11.0          11         JT        Maggie
11       10cm         2500.0        11.0          11         JT        Maggie
12       10cm         2000.0         0.0           0         JT        Maggie
14       10cm         2000.0         0.0           0         JT  Maggie/Angel
16       10cm         2000.0         0.0          12         JT        Maggie
18       10cm         2000.0         0.0          12         JT        Maggie
21       10cm         2000.0         0.0          11         JT        Maggie
23       10cm         2000.0         0.0          11         JT        Maggie
24       10cm         2500.0        12.0           0         JT        Maggie
26       10cm         2500.0        12.0           0         JT  Maggie/Angel
28       10cm         2500.0        12.0          12         JT        Maggie
30       10cm         2500.0        12.0          12         JT        Maggie
33       10cm         2500.0        12.0          11         JT        Maggie
35       10cm         2500.0        12.0          11         JT        Maggie
36       10cm         2500.0        11.0           0         JT        Maggie
38       10cm         2500.0        11.0           0         JT  Maggie/Angel
40       10cm         2500.0        11.0          12         JT        Maggie
42       10cm         2500.0        11.0          12         JT        Maggie
45       10cm         2500.0        11.0          11         JT        Maggie
47       10cm         2500.0        11.0          11         JT        Maggie
48       10cm         2000.0         0.0           0         JT        Maggie
50       10cm         2000.0         0.0           0         JT  Maggie/Angel
52       10cm         2000.0         0.0          12         JT        Maggie
54       10cm         2000.0         0.0          12         JT        Maggie
57       10cm         2000.0         0.0          11         JT        Maggie
59       10cm         2000.0         0.0          11         JT        Maggie
..        ...            ...         ...         ...        ...           ...
180      10cm         2500.0        11.0           0         JT        Maggie
182      10cm         2500.0        11.0           0         JT  Maggie/Angel
184      10cm         2500.0        11.0          12         JT        Maggie
186      10cm         2500.0        11.0          12         JT        Maggie
189      10cm         2500.0        11.0          11         JT        Maggie
191      10cm         2500.0        11.0          11         JT        Maggie
192      10cm         2500.0        11.0           0         JT        Maggie
194      10cm         2500.0        11.0           0         JT  Maggie/Angel
196      10cm         2500.0        11.0          12         JT        Maggie
198      10cm         2500.0        11.0          12         JT        Maggie
201      10cm         2500.0        11.0          11         JT        Maggie
203      10cm         2500.0        11.0          11         JT        Maggie
204      10cm         2000.0         0.0           0         JT        Maggie
206      10cm         2000.0         0.0           0         JT  Maggie/Angel
208      10cm         2000.0         0.0          12         JT        Maggie
210      10cm         2000.0         0.0          12         JT        Maggie
213      10cm         2000.0         0.0          11         JT        Maggie
215      10cm         2000.0         0.0          11         JT        Maggie
216      10cm         2000.0         0.0           0         JT        Maggie
218      10cm         2000.0         0.0           0         JT  Maggie/Angel
220      10cm         2000.0         0.0          12         JT        Maggie
222      10cm         2000.0         0.0          12         JT        Maggie
225      10cm         2000.0         0.0          11         JT        Maggie
227      10cm         2000.0         0.0          11         JT        Maggie
228      10cm         2500.0        12.0           0         JT        Maggie
230      10cm         2500.0        12.0           0         JT  Maggie/Angel
232      10cm         2500.0        12.0          12         JT        Maggie
234      10cm         2500.0        12.0          12         JT        Maggie
237      10cm         2500.0        12.0          11         JT        Maggie
239      10cm         2500.0        12.0          11         JT        Maggie

     CellCount (Vicell)  SeedDate    well_type
0             1670000.0  6/5/2017          exp
2             1240000.0  6/5/2017          exp
4             1530000.0  6/5/2017          exp
6             1150000.0  6/5/2017          exp
9              610000.0  6/5/2017          exp
11            1270000.0  6/5/2017          exp
12            1670000.0  6/5/2017  neg_control
14            1240000.0  6/5/2017  neg_control
16            1530000.0  6/5/2017  neg_control
18            1150000.0  6/5/2017  neg_control
21             610000.0  6/5/2017  neg_control
23            1270000.0  6/5/2017  neg_control
24            1670000.0  6/5/2017  pos_control
26            1240000.0  6/5/2017  pos_control
28            1530000.0  6/5/2017  pos_control
30            1150000.0  6/5/2017  pos_control
33             610000.0  6/5/2017  pos_control
35            1270000.0  6/5/2017  pos_control
36            1670000.0  6/5/2017          exp
38            1240000.0  6/5/2017          exp
40            1530000.0  6/5/2017          exp
42            1150000.0  6/5/2017          exp
45             610000.0  6/5/2017          exp
47            1270000.0  6/5/2017          exp
48            1670000.0  6/5/2017  neg_control
50            1240000.0  6/5/2017  neg_control
52            1530000.0  6/5/2017  neg_control
54            1150000.0  6/5/2017  neg_control
57             610000.0  6/5/2017  neg_control
59            1270000.0  6/5/2017  neg_control
..                  ...       ...          ...
180           1670000.0  6/5/2017          exp
182           1240000.0  6/5/2017          exp
184           1530000.0  6/5/2017          exp
186           1150000.0  6/5/2017          exp
189            610000.0  6/5/2017          exp
191           1270000.0  6/5/2017          exp
192           1670000.0  6/5/2017          exp
194           1240000.0  6/5/2017          exp
196           1530000.0  6/5/2017          exp
198           1150000.0  6/5/2017          exp
201            610000.0  6/5/2017          exp
203           1270000.0  6/5/2017          exp
204           1670000.0  6/5/2017  neg_control
206           1240000.0  6/5/2017  neg_control
208           1530000.0  6/5/2017  neg_control
210           1150000.0  6/5/2017  neg_control
213            610000.0  6/5/2017  neg_control
215           1270000.0  6/5/2017  neg_control
216           1670000.0  6/5/2017  neg_control
218           1240000.0  6/5/2017  neg_control
220           1530000.0  6/5/2017  neg_control
222           1150000.0  6/5/2017  neg_control
225            610000.0  6/5/2017  neg_control
227           1270000.0  6/5/2017  neg_control
228           1670000.0  6/5/2017  pos_control
230           1240000.0  6/5/2017  pos_control
232           1530000.0  6/5/2017  pos_control
234           1150000.0  6/5/2017  pos_control
237            610000.0  6/5/2017  pos_control
239           1270000.0  6/5/2017  pos_control

[120 rows x 14 columns]

In [19]:
df6[['ExperimentID', 'PassageNumber', 'Maintainer','GE_Initial','ChosenForPlating', 'PlateType', 'CellCount (Vicell)', 'SeedDate', 'FeedDate']]

,ExperimentID,PassageNumber,Maintainer,GE_Initial,ChosenForPlating,PlateType,CellCount (Vicell),SeedDate,FeedDate
0,exp1_20161021_seed,34,MH,Angel,1,6well,NaN,10/17/2016,NaN
1,exp1_20161021_seed,38,MH,Angel,1,6well,NaN,10/17/2016,NaN
2,exp1_20161021_seed,38,MH,Angel,1,6well,NaN,10/17/2016,NaN
3,exp2_20161025_seed,35,MH,Angel,1,6well,NaN,10/21/2016,NaN
4,exp2_20161025_seed,39,MH,Angel,1,6well,NaN,10/21/2016,NaN
5,exp2_20161025_seed,39,MH,Angel,1,6well,NaN,10/21/2016,NaN
6,exp3_20161028_seed,36,MH,Angel,1,6well,NaN,10/25/2016,NaN
7,exp3_20161028_seed,40,MH,Angel,1,6well,NaN,10/25/2016,NaN
8,exp3_20161028_seed,40,MH,Angel,1,6well,NaN,10/25/2016,NaN
9,exp4_20161031_seed,38,MH,Angel,1,6well,NaN,10/28/2016,NaN
10,exp4_20161031_seed,42,MH,Angel,1,6well,NaN,10/28/2016,NaN
11,exp4_20161031_seed,42,MH,Angel,1,6well,NaN,10/28/2016,NaN
12,exp5_20161104_seed,38,MH,Angel,1,6well,NaN,10/31/2016,NaN
13,exp5_20161104_seed,42,MH,Angel,1,6well,NaN,10/31/2016,NaN
14,exp5_20161104_seed,42,MH,Angel,1,6well,NaN,10/31/2016,NaN
15,exp6_20161107_seed,27,MH,Angel,1,6well,1900000.0,11/4/2016,NaN
16,exp6_20161107_seed,33,MH,Angel,1,6well,1577000.0,11/4/2016,NaN
17,exp6_20161107_seed,33,MH,Angel,1,6well,1340000.0,11/4/2016,NaN
18,exp7_20161111_seed,28,MH,Angel,1,6well,580000.0,11/7/2016,NaN
19,exp7_20161111_seed,34,MH,Angel,1,6well,564000.0,11/7/2016,NaN
20,exp7_20161111_seed,34,MH,Angel,1,6well,250000.0,11/7/2016,NaN
21,exp8_20161114_seed,25,AH,Angel,0,10cm,NaN,11/8/2016,NaN
22,exp8_20161114_seed,31,AH,Angel,0,10cm,NaN,11/8/2016,NaN
23,exp8_20161114_seed,31,AH,Angel,0,10cm,NaN,11/8/2016,NaN
24,exp8_20161114_seed,26,MH,Angel,1,10cm,1770000.0,11/11/2016,NaN
25,exp8_20161114_seed,26,AH,Angel,1,10cm,NaN,11/11/2016,NaN
26,exp8_20161114_seed,26,IAM,Angel,1,10cm,NaN,11/11/2016,NaN
27,exp8_20161114_seed,32,MH,Angel,1,10cm,1290000.0,11/11/2016,NaN
28,exp8_20161114_seed,32,AH,Angel,1,10cm,NaN,11/11/2016,NaN
29,exp8_20161114_seed,32,IAM,Angel,1,10cm,NaN,11/11/2016,NaN
...,...,...,...,...,...,...,...,...,...
642,4_20170616_seed,30,JT,NaN,0,10cm,NaN,6/16/2017,NaN
643,4_20170616_seed,30,JT,NaN,0,10cm,NaN,6/16/2017,NaN
644,4_20170616_seed,36,JT,NaN,1,10cm,920000.0,6/16/2017,NaN
645,4_20170616_seed,36,JT,NaN,0,10cm,NaN,6/16/2017,NaN
646,4_20170616_seed,40,JT,NaN,0,10cm,NaN,6/16/2017,NaN
647,4_20170616_seed,40,JT,NaN,0,10cm,NaN,6/16/2017,NaN
648,4_20170619_seed,31,JT,NaN,1,10cm,1410000.0,6/19/2017,NaN
649,4_20170619_seed,31,JT,NaN,0,10cm,NaN,6/19/2017,NaN
650,4_20170619_seed,31,JT,NaN,1,10cm,1590000.0,6/19/2017,NaN
651,4_20170619_seed,31,JT,NaN,0,10cm,NaN,6/19/2017,NaN
652,4_20170619_seed,37,JT,NaN,1,10cm,1220000.0,6/19/2017,NaN
653,4_20170619_seed,37,JT,NaN,0,10cm,NaN,6/19/2017,NaN
654,4_20170619_seed,37,JT,NaN,1,10cm,1160000.0,6/19/2017,NaN
655,4_20170619_seed,37,JT,NaN,0,10cm,NaN,6/19/2017,NaN
656,4_20170619_seed,41,JT,NaN,0,10cm,NaN,6/19/2017,NaN
657,4_20170619_seed,41,JT,NaN,1,10cm,930000.0,6/19/2017,NaN
658,4_20170619_seed,41,JT,NaN,0,10cm,NaN,6/19/2017,NaN
659,4_20170619_seed,41,JT,NaN,1,10cm,750000.0,6/19/2017,NaN
660,4_20170622_seed,32,JT,NaN,1,10cm,870000.0,6/22/2017,NaN
661,4_20170622_seed,32,JT,NaN,0,10cm,NaN,6/22/2017,NaN
662,4_20170622_seed,38,JT,NaN,1,10cm,1150000.0,6/22/2017,NaN
663,4_20170622_seed,38,JT,NaN,0,10cm,NaN,6/22/2017,NaN
664,4_20170622_seed,42,JT,NaN,1,10cm,710000.0,6/22/2017,NaN
665,4_20170622_seed,42,JT,NaN,0,10cm,NaN,6/22/2017,NaN
666,4_20170623_seed,32,JT,NaN,0,10cm,NaN,6/23/2017,NaN
667,4_20170623_seed,32,JT,NaN,0,10cm,NaN,6/23/2017,NaN
668,4_20170623_seed,38,JT,NaN,0,10cm,NaN,6/23/2017,NaN
669,4_20170623_seed,38,JT,NaN,0,10cm,NaN,6/23/2017,NaN
670,4_20170623_seed,42,JT,NaN,0,10cm,NaN,6/23/2017,NaN
671,4_20170623_seed,42,JT,NaN,0,10cm,NaN,6/23/2017,NaN